### ISSUE TITLE
Header "MongoSwiftMobile-Swift.h" not found

### ISSUE THREAD

**Issue by eldenchang** [mongodb/stitch-ios-sdk#100]
Hi, we are trying to use MongoDB for our ios project. After we did `pod install`, we could not compile our project due to the `Header "MongoSwiftMobile-Swift.h" not found` error. We have MongoSwiftMobile, StitchCore, StitchCoreSDk and StitchLocalMongoDBService directories inside in Pods folder. Don't know what to do at this point.
Thanks

**Comment by jsflax** [comment]
Hi Qifan,

What version of the iOS SDK are you using?

**Comment by jsflax** [comment]
Handling offline.

**Comment by jsflax** [comment]
Please try installing our latest version, 4.1.0. This cleans up our dependency graph that was causing the previous issues.
