### ISSUE TITLE
fix of mongodb website player

### ISSUE THREAD

**Issue by gauravsavanur07** [mongodb/stitch-ios-sdk#124]
I would like to fix the player stream function at MongoDB engineering website function

**Comment by adamchel** [comment]
Hi @gauravsavanur07 , I'm not sure I understand the question. Could you provide a link to what is not working?

**Comment by adamchel** [comment]
Thank you for bringing this to our attention, I have reported this issue internally and it will hopefully be resolved soon! I will close this issue as it is not related the Stitch iOS SDK.
