### ISSUE TITLE
Integrate with project that has Objective-C code

### ISSUE THREAD

**Issue by long1eu** [mongodb/stitch-ios-sdk#151]
Any docs on how to implement this in an ObjC project?

**Comment by jsflax** [comment]
There is no reliable way to do this at the moment. Our modules can be imported into Objective-C without issue, but none of our classes or methods are actually exposed.

**Comment by long1eu** [comment]
Would it be hard to get them exposed?

**Comment by jsflax** [comment]
It wouldn't necessarily be difficult, but we haven't done the research to check if it is doable.

Our modules were structured with only Swift in mind. While adding the `@objc` flag all over the codebase is simple enough, it would likely have side effects that would need to be solved, especially given our reliance on other libraries (including the Swift Mongo Driver).

All that said, there are future plans to make an Obj-C compatible SDK.

**Comment by long1eu** [comment]
I just spent a day trying to integrate it. Full of bitter I say with all my heart that I hate Everything related to stitch. Thanks.

**Comment by long1eu** [comment]
is there a rest endpoint that i can call with the custom jwt?
