### ISSUE TITLE
header "StitchCoreSDK-Swift.h" not found

### ISSUE THREAD

**Issue by gmack** [mongodb/stitch-ios-sdk#156]
I updated XCode to version 10.2, **however** I am still compiling with Swift version **4.2**, for the main target as well as all the pods, including StitchCore/StichCoreSDK.  I'm not using the embedded Mongo pods or anything else. 

All the Mongo-related pods are getting the same error as in the subject of this issue report, as well as my main target. 

It is always accompanied by: "Could not build Objective-C module 'StitchCore"

So it appears that the Stitch pods are not compatible with the new XCode, even though the version of Swift being used has not changed. 

I did update to Stitch pod 5.1.0 (was 5.0.0) but I got the same errors. Cleaning the build and rebuilding did not help, in either version of the pod.

**Comment by jsflax** [comment]
Unfortunately, it would appear that our dependencies need to update to XCode 10.2 as well before we can update our own.

I'll keep this issue open and notify you when this is fixed.

**Comment by gmack** [comment]
Thank you @jsflax , at least I know this issue is confirmed, and it's not something I'm doing wrong! 
Perhaps as part of the fix or upgrade, you could explain why this particularly obscure aspect of the build was so fragile. Search paths for headers should be stable no?  Xcode strikes again...

**Comment by adhigadu** [comment]
hi @jsflax any update on this?

**Comment by adamchel** [comment]
Hi everyone,

As of Release 6.0.0, we now support Swift 5 and Xcode 10.2: https://github.com/mongodb/stitch-ios-sdk/releases/tag/6.0.0.

Let us know if you encounter any other issues.
