### ISSUE TITLE
Please add Swift 5 support.

### ISSUE THREAD

**Issue by FeedMyTummy** [mongodb/stitch-ios-sdk#160]

**Comment by long1eu** [comment]
Any news on this?
I can't compile my app because of this.

**Comment by FeedMyTummy** [comment]
You can continue to develop under the previous version of Xcode/Swift for the time being. An update will come to fix the issue with Xcode 10.2 but there is not ETA. If you have or have found any answers/workarounds, please contribute below.

https://stackoverflow.com/questions/55445611/mongoswift-pod-contains-100-compiler-errors-unable-to-build-after-install/55544074#55544074

**Comment by long1eu** [comment]
So I should go back to Hight Sierra but be able to user this pod, right?

**Comment by FeedMyTummy** [comment]
You can use the latest version of MacOS. I am using 10.14.4. You just need the older version of Xcode. Such as Xcode 10.1 which can be downloaded from https://developer.apple.com/xcode/downloads.

**Comment by long1eu** [comment]
Got it. Thanks

**Comment by joccacog** [comment]
Xcode 10.2 wouldn't Build Stich iOS SDK for me either. Tech Support told me to try:

pod 'StitchSDK', '= 6.0.0-beta.1'

It seems to be working...

**Comment by FeedMyTummy** [comment]
Yes. Version 6.0.0 of the SDK fixes this issue. I’ve closed this issue.
