### ISSUE TITLE
CocoaPods could not find compatible versions for pod StitchSDK

### ISSUE THREAD

**Issue by relatedcode** [mongodb/stitch-ios-sdk#203]
Hi there,

I am trying to install the latest version of StitchSDK (6.4.0) using CocoaPods. I follow your instructions, however I get the follwoing error.

```
[!] CocoaPods could not find compatible versions for pod "StitchSDK":
  In Podfile:
    StitchSDK (= 6.4.0)

None of your spec sources contain a spec satisfying the dependency: `StitchSDK (= 6.4.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
The Podfile looks like this:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'app' do
	pod 'StitchSDK', '= 6.4.0'
end
```
And I am using this command `pod install --repo-update` with no luck. Any advice? Thanks!

**Comment by relatedcode** [comment]
I have also tried this option:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'app' do
	pod 'StitchSDK', :git => "https://github.com/mongodb/stitch-ios-sdk.git", :branch => "master", :tag => "6.4.0"
end
```
But I also have an error:
```
[!] CocoaPods could not find compatible versions for pod "StitchRemoteMongoDBService":
  In Podfile:
    StitchSDK (from `https://github.com/mongodb/stitch-ios-sdk.git`, branch `master`, tag `6.4.0`) was resolved to 6.4.0, which depends on
      StitchSDK/StitchSDK (= 6.4.0) was resolved to 6.4.0, which depends on
        StitchSDK/StitchRemoteMongoDBService (= 6.4.0) was resolved to 6.4.0, which depends on
          StitchRemoteMongoDBService (= 6.4.0)

None of your spec sources contain a spec satisfying the dependency: `StitchRemoteMongoDBService (= 6.4.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by relatedcode** [comment]
I can use the 6.3.0 version with the following setup.
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'app' do
	pod 'StitchRemoteMongoDBService'
end
```

**Comment by jsflax** [comment]
It’s looking like there may have been an issue in the release process. I will fix this today.

**Comment by relatedcode** [comment]
@jsflax Thank you! :)

**Comment by awu-atomerse** [comment]
Any update on this? It's been two months and we still cannot find pod 6.4.0

**Comment by ahmetfg** [comment]
same here
`
[!] CocoaPods could not find compatible versions for pod "StitchSDK":
  In Podfile:
    StitchSDK (~> 6.4.0)
`

**Comment by si-hartmann** [comment]
Any progress on this? Seems there is not much maintenance done for this SDK :-(

**Comment by mclimb** [comment]
I'm having the same issue. I was only able to install it with: `pod 'StitchSDK', '~> 6.1.0'`

**Comment by ahmetfg** [comment]
I think we deserve an answer??

**Comment by jsflax** [comment]
@ahmetfg @mclimb @si-hartmann @relatedcode This should now be fixed. Apologies for the delay. If someone can confirm on their end that this has been fixed, we can close out this ticket.

**Comment by si-hartmann** [comment]
@jsflax Yes, I was able to upgrade to 6.4.0 and build (although the build is still crashing when building with Xcode 11.4) 

So this can be closed.

**Comment by jsflax** [comment]
I'll look into the Xcode 11.4 crashes separately. Thanks!
