### ISSUE TITLE
3.0.0 not published to cocoapods

### ISSUE THREAD

**Issue by apparentvisuals** [mongodb/stitch-ios-sdk#33]
Will new versions be published to cocoapods or best to use manual install?

**Comment by edaniels** [comment]
3.0.0 isn't quite yet ready for release. There are a few more changes to get in and we are waiting for PromiseKit 5 to be published.

**Comment by jsflax** [comment]
@apparentvisuals , we will be publishing to Cocoapods regularly once releases are complete. `3.0.1` has just been released and is ready for use!
