### ISSUE TITLE
Unable to find a specification for `StitchSDK (~> 4.0.0)`

### ISSUE THREAD

**Issue by Aaron-A** [mongodb/stitch-ios-sdk#81]
I'm unable to import the core functionality via pod 'StitchSDK', '~> 4.0.0' || pod 'StitchSDK'

//Uncomment the next line to define a global platform for your project
//platform :ios, '9.0'

target 'Mongo' do
  //Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  // Pods for Mongo
 // For core functionality and the Remote MongoDB Service
     pod 'StitchSDK', '~> 4.0.0'

  target 'MongoTests' do
    inherit! :search_paths
    // Pods for testing
  end

  target 'MongoUITests' do
    inherit! :search_paths
    // Pods for testing
  end

end

**Comment by jsflax** [comment]
Hi there!

Even though the pod is StitchSDK, the import structure is still relative to its dependencies.

To access core functionality, you would `import StitchCore`, and to access the remote mongodb service, you would `import StitchRemoteMongoDBService`.

Does that clear up the import issue?

**Comment by Aaron-A** [comment]
pod repo update along with updating cocopods seemed to do the trick. Thanks for the help.
