### ISSUE TITLE
OSError when os.remove in build_frameworks.py

### ISSUE THREAD

**Issue by humberthumbert** [mongodb/stitch-ios-sdk#95]
I was trying to follow the instruction and connect mongodb into my ios project . However, every time when it comes to installing StitchCoreSDK, it fails and gives the following message:
`Traceback (most recent call last):
  File "scripts/build_frameworks.py", line 158, in <module>
    fix_mongoc_symlinks(variant)
  File "scripts/build_frameworks.py", line 46, in fix_mongoc_symlinks
    os.remove('{}/lib/libbson-1.0.dylib'.format(variant.name))
OSError: [Errno 2] No such file or directory: 'iphoneos/lib/libbson-1.0.dylib'
`
Is that just a personal problem?

**Comment by jsflax** [comment]
Hi Lifan,

This is a known issue with building master against Swift 4.2. Once
https://github.com/mongodb/stitch-ios-sdk/pull/94 is merged, this will be
sorted.

Thanks for your patience!

**Comment by jsflax** [comment]
Hi @humberthumbert ,

Could you give this another try? If you pull from master, it should be fixed now.

**Comment by humberthumbert** [comment]
Great Thanks! It works fine now.
