### ISSUE TITLE
Cannot find Pods-<ProjectName>.debug.xcconfig

### ISSUE THREAD

**Issue by humberthumbert** [mongodb/stitch-ios-sdk#96]
Hey, me again. After I pod install successfully, I encountered another problem saying that xcode could not find the Pods-'ProjectName'.debug.xcconfig file which should be located in 
'Your ProjectDir'/**Pods**/Target Support Files/Pods 'ProjectName'/ 
and the error message it gave me indicated that it was trying to find the file in 
'Your ProjectDir'/**Pods/Pods**/Target Support Files/Pods 'ProjectName'/.

I just solved it by duplicating the Pods directory in it. Again I am not sure if it only happened to me.

**Comment by jsflax** [comment]
Hey again,

Are you able to reproduce this at all? That sounds like it could be a caching issue with Pods more so than Stitch related. Happy to talk it out though.

**Comment by jsflax** [comment]
Please try installing our latest version, 4.1.0. This cleans up our dependency graph that was causing the previous issues.
