### ISSUE TITLE
Error installing with Pods

### ISSUE THREAD

**Issue by ETGgames** [mongodb/stitch-ios-sdk#97]
Creating a new iOS project from scratch, pod install with the pod 'StitchSDK' gives error:

`

[!] /bin/bash -c 
set -e
sh scripts/download_dependencies.sh;
python scripts/build_frameworks.py;

Cloning into 'mod-pbxproj'...
Note: checking out '5b3166626cbd4bfcb811a24761fe33be1d177341'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

 -=O=-#   #   #     #                                                         
-=O#- #  #    #                                                               
  -=O=#   #   #     #                                                         
-=O#- #  #    #       
Traceback (most recent call last):
  File "scripts/build_frameworks.py", line 1, in <module>
    from frameworkify import (
  File "/Users/user/Library/Caches/CocoaPods/Pods/Release/StitchCoreSDK/4.0.6-6a045/scripts/frameworkify/__init__.py", line 1, in <module>
    from modules import Module, SwiftModule
ModuleNotFoundError: No module named 'modules'

`

The podfile looks like this:

target 'testiOS' do
use_frameworks!
pod 'StitchSDK', '~> 4.0.5'
end

**Comment by jsflax** [comment]
It looks like we'll need to do an independent release for the `StitchSDK`
pod. I'll set up a release for the morning.

**Comment by ETGgames** [comment]
Just downgraded default python to 2.7 and tried installing and it worked!

**Comment by jsflax** [comment]
Please try installing our latest version, 4.1.0. This cleans up our dependency graph that was causing the previous issues.
