### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by marcoaras** [mongodb/stitch-ios-sdk#98]
Pod install fails as below:

### POD FILE

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Proj' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proj
    pod 'StitchSDK', '~> 4.0.1'
end
```

### pod install on terminal 

Installing StitchCore (4.0.5) OK
Installing StitchCoreRemoteMongoDBService (4.0.5) OK
Installing StitchCoreSDK (4.0.6) FAIL
[!] /bin/bash -c 
set -e
sh scripts/download_dependencies.sh;
python scripts/build_frameworks.py;

downloaded 18166957 of 18166957 bytes (100.00%)
arm64-apple-ios10.2
xcrun -sdk iphoneos swiftc -F./Frameworks/iphone/iphoneos MongoSwift/Collection.swift MongoSwift/SDAM.swift MongoSwift/Client.swift MongoSwift/Database.swift MongoSwift/MongoSwift.swift MongoSwift/ReadWriteConcern.swift MongoSwift/Cursor.swift MongoSwift/MongoError.swift MongoSwift/ClientSession.swift MongoSwift/APM.swift MongoSwift/BSON/BsonEncoder.swift MongoSwift/BSON/Document+Codable.swift MongoSwift/BSON/BsonDecoder.swift MongoSwift/BSON/CodableNumber.swift MongoSwift/BSON/Document.swift MongoSwift/BSON/BsonValue.swift -o .tmp/MongoSwift/iphoneos/MongoSwift -target arm64-apple-ios10.2 -emit-module -emit-objc-header -emit-library -embed-bitcode
error: could not generate output file map for MongoSwift
######################################################################## 100.0%
Cloning into 'mod-pbxproj'...
Note: checking out '5b3166626cbd4bfcb811a24761fe33be1d177341'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

######################################################################## 100.0%
Traceback (most recent call last):
  File "scripts/build_frameworks.py", line 190, in <module>
    SwiftFrameworkModule(mongoswift.create_module(platform, variant, min_version)).create('Frameworks'))
  File "/Users/myuser/Library/Caches/CocoaPods/Pods/Release/StitchCoreSDK/4.0.6-6a045/scripts/frameworkify/frameworks.py", line 309, in create
    self.module.platform, self.module.variant, output_dir)
  File "/Users/myuser/Library/Caches/CocoaPods/Pods/Release/StitchCoreSDK/4.0.6-6a045/scripts/frameworkify/frameworks.py", line 158, in create
    super(FrameworkModule, self).create(platform, variant, output_dir)
  File "/Users/myuser/Library/Caches/CocoaPods/Pods/Release/StitchCoreSDK/4.0.6-6a045/scripts/frameworkify/frameworks.py", line 51, in create
    copy2(self.library_path, self.bin_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '.tmp/MongoSwift/iphoneos/MongoSwift'

**Comment by jsflax** [comment]
Hi Aras,

Could you try upgrading cocoapods to 1.6? Let me know if that works. Thanks!

**Comment by marcoaras** [comment]
Hi,

No its same, my version is /Users/arascagli/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods.rb

Aras Cagliuzun
cagliuzun.aras@gmail.com

**Comment by jsflax** [comment]
Could you also try clearing out your pods directory? I'm having a bit of
trouble reproducing and could use as much data as possible so that we can
get a release out as soon as possible.

**Comment by jsflax** [comment]
What version of macosx are you on?

**Comment by marcoaras** [comment]
I cleaned all pod cache and install new version. But error is the same. My MacOs version is Mojave Version 10.14



Aras Cagliuzun
cagliuzun.aras@gmail.com

**Comment by jsflax** [comment]
And what version of XCode?

**Comment by marcoaras** [comment]
Xcode version is Version 10.0 (10A255)


Aras Cagliuzun
cagliuzun.aras@gmail.com

**Comment by jsflax** [comment]
Try running `rm -rf /Users/myuser/Library/Caches/CocoaPods/`. Also it shouldn't matter, but, try     upgrading the StitchSDK pod to 4.0.5.

Is there any more information you can give me?

**Comment by marcoaras** [comment]
Hi again,

I did what you recommended, but still get the same error. 

IOError: [Errno 2] No such file or directory: '.tmp/MongoSwift/iphoneos/MongoSwift'

Aras Cagliuzun
cagliuzun.aras@gmail.com

**Comment by marcoaras** [comment]
Hi Jason,

I tried bunch of steps below

1. `rm -rf ~/Library/Caches/CocoaPods`
2. `rm -rf Pods` 
3. `rm -rf ~/Library/Developer/Xcode/DerivedData/*` 
4. `pod deintegrate` 
5. `pod setup` 
6. `pod install`

However I still getting the same problem. 

When I tried to understand what is the problem, I research  deep inside. Then  I saw that ~⁨/Library⁩/Caches⁩/⁨CocoaPods⁩/⁨Pods⁩/⁨Release⁩/⁨StitchCoreSDK⁩/⁨4.0.6-6a045⁩/Frameworks⁩/iphone⁩/⁨iphoneos/MongoSwift.framework is empty. Somehow my system can not download this framework. Then I get IOError: [Errno 2] No such file or directory: '.tmp/MongoSwift/iphoneos/MongoSwift'

How can I solve this problem? Do you have any solution for it?

Thank you.⁩

**Comment by jsflax** [comment]
What version of python are you running?

**Comment by marcoaras** [comment]
python v: 2.7

**Comment by jsflax** [comment]
My version of ruby is `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]` and my version of gems is `2.7.6`. Could you try upgrading those as well?

**Comment by marcoaras** [comment]
I update my ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16] and my gem version is 2.7.7 but still same cans download MongoSwift.framework at the time of pod install

**Comment by jsflax** [comment]
This one is a doozy!

If it's okay by you, try giving our repo a clone, and then run make:
```
git clone https://github.com/mongodb/stitch-ios-sdk/
cd stitch-ios-sdk
make
```

Then please paste the output from the `make` script. It should give us a deeper hint as to what is happening, since it seems that either the MongoSwift binary is not being built, or not being written to disk.

**Comment by marcoaras** [comment]
Same problem... you can find make output below. Same error gave me as pod install.

>  since it seems that either the MongoSwift binary is not being built, or not being written to disk.

Yes maybe you are right, however if you look files after pod install successfully done, you will see framework files in MongoSwift.framework path `Any⁩Proj/Pods⁩/⁨StitchCoreSDK⁩/⁨Frameworks⁩/⁨ios⁩/⁨MongoSwift.framework⁩/`  . These files should have been copied from `Users⁩/⁨myuser/⁨Library⁩/⁨Caches⁩/⁨CocoaPods⁩/Pods⁩/⁨Release⁩/⁨StitchCoreSDK⁩/⁨4.0.6-6a045⁩/Frameworks⁩/⁨iphone⁩/iphoneos⁩/MongoSwift.framework⁩`


Please check your email I sent you screenshots of cocoacache folder and succesfully pod installed sample project files. (Sample project created another computer.)



**Output of make**
Macintosh-2:GitClones myuser$ make
make: *** No targets specified and no makefile found.  Stop.
Macintosh-2:GitClones myuser$ cd stitch-ios-sdk
Macintosh-2:stitch-ios-sdk myuser$ make
sh scripts/download_dependencies.sh
######################################################################## 100.0%
Cloning into 'mod-pbxproj'...
remote: Enumerating objects: 1793, done.
remote: Total 1793 (delta 0), reused 0 (delta 0), pack-reused 1793
Receiving objects: 100% (1793/1793), 434.13 KiB | 134.00 KiB/s, done.
Resolving deltas: 100% (1143/1143), done.
Note: checking out '5b3166626cbd4bfcb811a24761fe33be1d177341'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
python scripts/build_frameworks.py
downloaded 18166957 of 18166957 bytes (100.00%)
arm64-apple-ios10.2
xcrun -sdk iphoneos swiftc -F./Frameworks/iphone/iphoneos MongoSwift/Collection.swift MongoSwift/SDAM.swift MongoSwift/Client.swift MongoSwift/Database.swift MongoSwift/MongoSwift.swift MongoSwift/ReadWriteConcern.swift MongoSwift/Cursor.swift MongoSwift/MongoError.swift MongoSwift/ClientSession.swift MongoSwift/APM.swift MongoSwift/BSON/BsonEncoder.swift MongoSwift/BSON/Document+Codable.swift MongoSwift/BSON/BsonDecoder.swift MongoSwift/BSON/CodableNumber.swift MongoSwift/BSON/Document.swift MongoSwift/BSON/BsonValue.swift -o .tmp/MongoSwift/iphoneos/MongoSwift -target arm64-apple-ios10.2 -emit-module -emit-objc-header -emit-library -embed-bitcode
error: could not generate output file map for MongoSwift
Traceback (most recent call last):
  File "scripts/build_frameworks.py", line 190, in <module>
    SwiftFrameworkModule(mongoswift.create_module(platform, variant, min_version)).create('Frameworks'))
  File "/Users/myuser/Documents/GitClones/stitch-ios-sdk/scripts/frameworkify/frameworks.py", line 309, in create
    self.module.platform, self.module.variant, output_dir)
  File "/Users/myuser/Documents/GitClones/stitch-ios-sdk/scripts/frameworkify/frameworks.py", line 158, in create
    super(FrameworkModule, self).create(platform, variant, output_dir)
  File "/Users/myuser/Documents/GitClones/stitch-ios-sdk/scripts/frameworkify/frameworks.py", line 51, in create
    copy2(self.library_path, self.bin_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '.tmp/MongoSwift/iphoneos/MongoSwift'
make: *** [all] Error 1
Macintosh-2:stitch-ios-sdk myuser$

**Comment by jsflax** [comment]
We will be releasing a new version in the next couple days that covers this
issue.

**Comment by jsflax** [comment]
Please try installing our latest version, 4.1.0. This cleans up our dependency graph that was causing the previous issues.

**Comment by marcoaras** [comment]
Thank you... great job :)



Aras Cagliuzun
cagliuzun.aras@gmail.com
